site_name: waio
name: waio
site_description: Awesome WhatsAPP framework
site_author: dotX12
repo_name: dotX12/waio
repo_url: https://github.com/dotX12/waio
edit_uri: edit/master/docs/

extra:
  disqus: ""
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/waioru
      name: Russian Chat

nav:
  - HUB: index.md
  - Tutorial:
      - Content of the tutorial: tutorial/index.md
      - First bot: tutorial/first-bot.md
      - Filter rules: tutorial/filters.md

theme:
  name: material
  language: en

  features:
    - content.code.annotate

  palette:
    scheme: slate
    primary: black
    accent: blue

  font:
    text: Roboto Mono
    code: Monaco

  favicon: logo.png

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.magiclink
  - toc:
      permalink: True
  - pymdownx.snippets:
      check_paths: true

extra_css:
  - _css/style.css